#!/bin/bash
# Function to show usage
usage() {
  echo "Usage: $0 [-r]"
  echo "  -r  Install Ansible Roles and other requirements"
  exit 1
}

# Function to install requirements
install_requirements() {
  ansible-galaxy install -r requirements.yml --force
}

# Parse command line arguments
while getopts ":r" option; do
  case "${option}" in
    r)
      install_requirements
      exit 0
      ;;
    *)
      usage
      ;;
  esac
done

# If no arguments are provided, run all commands
if [ ${OPTIND} -eq 1 ]; then
  sudo apt update
  sudo apt install -y software-properties-common
  sudo apt-add-repository --yes --update ppa:ansible/ansible
  sudo apt install -y ansible
  install_requirements
fi