- hosts: localhost 
  tags: pi 
  roles:
    - role: ubuntu
      vars:
        nerd_font: FiraCode
      tags: [ubuntu]
    - common
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ lookup('env', 'USER') }}"
          - root
        docker_install_compose: true
      tags: [docker]
    - role: raspberrypi
      vars:
        dist_update: false
