---
- name: Install packages specific to Odroid SBCs
  package:
    name: "{{ item }}"
    state: present
  loop:
    - device-tree-compiler
    - v4l-utils
    - build-essential
    - dkms
    - network-manager
    - ufw
  become: true
  tags: [packages]

- name: Include network configuration tasks
  import_tasks: "network.yml"
  tags: [network]

- name: Include gpio configuration tasks
  import_tasks: "gpio.yml"
  tags: [gpio]

- name: Include UFW configuration tasks
  import_tasks: "ufw.yml"
  tags: [ufw firewall]
