---
- name: reload NetworkManager configuration
  ansible.builtin.command: nmcli connection reload
  become: true

- name: reload udev rules
  ansible.builtin.shell: udevadm control --reload-rules && udevadm trigger
  become: true

- name: restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  become: true
