# tasks file for ubuntu
- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - v4l-utils
    - alsa-utils
    - build-essential
    - ufw
  become: true
  tags: [packages]

- name: Install fonts
  import_tasks: "nerd_fonts.yml"
  tags: [fonts]

- name: Include UFW configuration tasks
  import_tasks: "ufw.yml"
  tags: [ufw firewall]

- name: Install pyopenssl python package
  ansible.builtin.pip:
    name: pyopenssl
    extra_args: --break-system-packages
  become: true
