---
- name: Check if swap is turned on
  shell: free | awk '/^Swap:/ {exit $2 != 0}'
  register: swap_active
  ignore_errors: true
  changed_when: false

- name: Set should_disable
  set_fact:
    should_disable: "{{ swap_active.rc == 1 }}"

- debug: 
    msg: "The flag for disabling and rebuilding the swap file is: {{ should_disable }}"

- name: Disable existing swap
  become: true
  command: swapoff -a
  register: swapoff_result
  retries: 3
  delay: 5
  until: swapoff_result is success
  when: should_disable
  ignore_errors: true

- name: Wait for swap to be fully disabled
  command: grep -v /swapfile /proc/swaps
  register: swap_disabled
  retries: 3
  delay: 5
  until: swap_disabled.rc == 0
  when: should_disable

- name: Remove old swap file
  become: true
  file:
    path: /swapfile
    state: absent
  register: result
  when: should_disable

- name: Allocate the swap file using dd
  become: true
  command: dd if=/dev/zero of=/swapfile bs=1MB count={{ swap.size_gb * 1024 }}

- name: Change permission of the swap file
  become: true
  file:
    path: /swapfile
    mode: "0600"

- name: Create a swap area on the swap file
  become: true
  command: mkswap /swapfile

- name: Activate the swap file as a swap memory
  become: true
  command: swapon /swapfile

- name: Append configuration in /etc/fstab
  become: true
  lineinfile:
    path: /etc/fstab
    line: "/swapfile swap swap defaults 0 0"
    create: yes

- name: Set swappiness level
  become: true
  command: sysctl vm.swappiness={{ swap.swappiness }}

- name: Append configuration in /etc/sysctl.conf
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    line: "vm.swappiness={{ swap.swappiness }}"
    create: yes

- name: Check if swap file exists
  stat:
    path: /swapfile
  register: swapfile_exists

- name: Verify swap is active
  shell: swapon --show | grep -q '^/swapfile'
  register: swap_active
  ignore_errors: true

- name: Assert swap file is properly configured
  assert:
    that:
      - swapfile_exists.stat.exists
      - swap_active is success
    fail_msg: "Swap file verification failed. Exists: {{ swapfile_exists.stat.exists }}, Active: {{ swap_active is success }}"
