- name: Ensure ufw is installed.
  package:
    name: ufw
    state: present
  become: true

- name: Configure open ports with ufw
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { rule: allow, port: 22, proto: tcp }
    - { rule: allow, port: 80, proto: tcp }
    - { rule: allow, port: 443, proto: tcp }
  become: true

- name: Configure default incoming/outgoing rules with ufw
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }
  become: true
