- name: Ensure ufw is installed.
  package:
    name: ufw
    state: present
  become: true

- name: Ensure that the port for pivpn is open 
  ufw:
    rule: allow 
    port: "{{ pivpn_port }}"
    proto: udp
  become: true

- name: Download PiVPN install script
  get_url:
    url: https://install.pivpn.io
    dest: /tmp/install.sh
    mode: '0755'

- name: Create PiVPN configuration file from template
  template:
    src: pivpn.conf.j2
    dest: "{{ pivpn_config_path }}"
    mode: '0644'

- name: Run PiVPN install script
  command: 
    cmd: "/tmp/install.sh --unattended {{ pivpn_config_path }}"

- name: Copy archive from role files directory to remote server
  copy:
    src: "pivpnwgbackup.tgz"
    dest: "/tmp/pivpnwgbackup.tgz"
    mode: '0644'

- name: Extract archive to root directory
  ansible.builtin.unarchive:
    src: "/tmp/pivpnwgbackup.tgz"
    dest: "/"
    remote_src: yes
  become: yes  # This is equivalent to using sudo
