---
- name: Remove files that will conflict with Stow
  ansible.builtin.file:
    path: "{{ [home, item] | path_join }}"
    state: absent
  loop:
    - .zshrc
    - .bashrc
    - .profile
    - .p10k.zsh
    - .lynxrc
    - ".local/bin/cht.sh"
    - .vimrc
    - .inputrc
    - .editrc
    - ".config/nvim/init.vim"
    - ".config/neofetch/config.conf"
    - ".config/htop/htoprc"
    - ".config/gh/config.yml"
    - ".config/lazygit/config.yml"
    - ".config/bat/config"

# clone the dotfiles repo and stow the files
- name: Clone the dotfiles repo
  ansible.builtin.git:
    repo: 'https://github.com/tomasort/dotfiles'
    dest: "{{ [home, 'dotfiles'] | path_join }}"
    clone: true
    force: true

- name: Run stow
  ansible.builtin.shell: "stow . --verbose=2"
  args:
    chdir: "{{ [home, 'dotfiles'] | path_join }}"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
