---
- name: Ensure fail2ban is Installed.
  apt:
    name: fail2ban 
    state: present 
    when: ansible_os_family == 'Debian'
  become: true

- name: Ensure fail2ban is running and enabled on boot.
  service:
    name: fail2ban 
    state: started 
    enabled: yes
  become: true