# Git configuration
- name: Ensure git is installed.
  package:
    name: git
    state: present
  become: true

- name: Git personal setup email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"

- name: Git personal setup name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"

- name: Set Git color UI to auto
  community.general.git_config:
    name: color.ui
    scope: global
    value: auto

- name: Enable rerere in git
  community.general.git_config:
    name: rerere.enabled
    scope: global
    value: true

# We could even set up github here with gh
- name: Make sure gh is installed
  package:
    name: gh
    state: present
  become: true

- name: Authenticate on Github
  ansible.builtin.shell:
    cmd: echo {{ github_token }} | gh auth login --git-protocol ssh --with-token

- name: Download lazygit
  ansible.builtin.git:
    repo: "https://github.com/jesseduffield/lazygit.git"
    dest: /tmp/lazygit

- name: Install lazygit
  ansible.builtin.command: go install
  args:
    chdir: /tmp/lazygit
  environment:
    PATH: "/usr/local/go/bin:{{ path }}"
