---
- name: Check if Go is already installed
  command: /usr/local/go version
  ignore_errors: true
  register: go_version_result
  changed_when: false
  become: true

- name: Remove current installation if outdated
  file:
    state: absent
    path: /usr/local/go
  when:
    - go_version_result is succeeded
    - go_version not in go_version_result.stdout
  become: true

- name: Download Go tarball
  get_url:
    url: "{{ go_download_url }}"
    dest: "/tmp/{{ go_tarball }}"
  when: go_version_result is failed
        or go_version not in go_version_result.stdout
  become: true

- name: Extract Go tarball
  unarchive:
    src: "/tmp/{{ go_tarball }}"
    dest: "/usr/local"
    remote_src: yes
  when: go_version_result is failed
        or go_version not in go_version_result.stdout
  become: true
