---
# tasks file for common
- name: Install minimal packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - stow
    - git
    - vim
    - curl
    - nmap
    - iftop
    - jq
    - gh
    - bat
  become: true
  tags: [ packages, minimal ]

- name: Install extra packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - moreutils
    - wget
    - npm
    - tmux
    - tree
    - openvpn
    - cloc
    - httrack
    - pwgen
    - ffmpeg
    - hashcat
  become: true
  tags: [ packages ]

- name: Install packages not for MacOS
  package:
    name: "{{ item }}"
    state: present
  loop:
    - htop # there is a cooler version for macos
    - handbrake
    - x11-apps
  become: true
  when: ansible_os_family != 'Darwin'
  tags: [ packages ]

- name: Include zsh tasks 
  import_tasks: "zsh.yml"
  tags: [ zsh, dotfiles, shell, minimal ]

- name: Include git tasks 
  import_tasks: "git.yml"
  tags: [ git, minimal ]

- name: Include vim tasks 
  import_tasks: "vim.yml"
  tags: [ vim, minimal ]

- name: Include python tasks
  import_tasks: "python.yml"
  tags: [ python ]

- name: Include ssh tasks
  import_tasks: "ssh.yml"
  tags: [ ssh, minimal ]

- name: Include x11 tasks
  import_tasks: "x11.yml"
  tags: [ x11, minimal ]

- name: Include fail2ban tasks
  import_tasks: "fail2ban.yml"
  tags: [ fail2ban, minimal ]

- name: Include tmux tasks
  import_tasks: "tmux.yml"
  tags: [ tmux, minimal ]

- name: Include node tasks
  import_tasks: "node.yml"
  tags: [ node, minimal ]

- name: Remove unused packages.
  package:
    name:
      - nano
      - sendmail
    state: absent
    purge: yes
  become: true
  tags: [ packages, cleanup, minimal ]
