---
# tasks file for common
- name: Install required/minimal packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - stow
    - git
    - vim
    - curl
    - nmap
    - iftop
    - jq
    - gh
    - bat
    - ripgrep
    - composer
    - php
    - luarocks
    - maven
    - xclip
    - xsel # for cht.sh
    - rlwrap # for cht.sh
    - git-lfs
    - neofetch
  become: true
  tags: [packages, minimal, required]

- name: Install extra packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - moreutils
    - wget
    - npm
    - tmux
    - tree
    - openvpn
    - cloc
    - httrack
    - pwgen
    - ffmpeg
    - hashcat
  become: true
  tags: [packages]

- name: Install packages not for MacOS
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - htop # there is a cooler version for macos
    - handbrake
    - x11-apps
  become: true
  when: ansible_os_family != 'Darwin'
  tags: [packages]

- name: Install Go for Linux {{ go_arch }}
  ansible.builtin.import_tasks: "go.yml"
  when: ansible_os_family != 'Darwin'
  tags: [go]

- name: Install go for MacOs
  ansible.builtin.package:
    name: go
    state: present
  become: true
  when: ansible_os_family == 'Darwin'
  tags: [go]

- name: Include nvim tasks
  ansible.builtin.import_tasks: "nvim.yml"
  tags: [nvim, minimal]

- name: Include zsh tasks
  ansible.builtin.import_tasks: "zsh.yml"
  tags: [zsh, dotfiles, shell, minimal]

- name: Stow dotfiles
  ansible.builtin.import_tasks: "dotfiles.yml"
  tags: [dotfiles, minimal]

- name: Include git tasks
  ansible.builtin.import_tasks: "git.yml"
  tags: [git, minimal]

# - name: Include vim tasks
#   ansible.builtin.import_tasks: "vim.yml"
#   tags: [vim, minimal]

- name: Include python tasks
  ansible.builtin.import_tasks: "python.yml"
  tags: [python]

- name: Include ssh tasks
  ansible.builtin.import_tasks: "ssh.yml"
  tags: [ssh, minimal]

- name: Include x11 tasks
  ansible.builtin.import_tasks: "x11.yml"
  tags: [x11, minimal]

- name: Include fail2ban tasks
  ansible.builtin.import_tasks: "fail2ban.yml"
  tags: [fail2ban, minimal]

- name: Include tmux tasks
  ansible.builtin.import_tasks: "tmux.yml"
  tags: [tmux, minimal]

- name: Include node tasks
  ansible.builtin.import_tasks: "node.yml"
  tags: [node, minimal]

- name: Include rust tasks
  ansible.builtin.import_tasks: "rust.yml"
  tags: [rust, minimal]

- name: Remove unused packages.
  ansible.builtin.package:
    name:
      - nano
      - sendmail
    state: absent
    purge: true
  become: true
  tags: [packages, cleanup, minimal]
