---
- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "{{ home }}/.nvm/nvm.sh"

- name: Install Node
  ansible.builtin.shell: nvm install --lts

- name: Install pnpm
  ansible.builtin.shell: >
    curl -fsSL https://get.pnpm.io/install.sh | sh -

- name: Install global packages with npm
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - typescript
    - eslint
    - prettier
    - neovim
    - vite
