---
# Tasks to install neovim

- name: Check if nvim is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/nvim
  register: nvim_installed

- name: Clone Neovim stable branch
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "/tmp/neovim"
    version: stable
  when: not nvim_installed.stat.exists

- name: Install nvim build dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - ninja-build
    - gettext
    - cmake
    - curl
    - build-essential
  when: not nvim_installed.stat.exists

- name: Build nvim
  community.general.make:
    chdir: /tmp/neovim
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: not nvim_installed.stat.exists

- name: Install nvim
  become: true
  community.general.make:
    chdir: /tmp/neovim
    target: install
  when: not nvim_installed.stat.exists

- debug: 
    msg: "The home directory is: {{ home }}"

- name: Ensure autoload directory exists
  ansible.builtin.file:
    path: "{{ [home, '.local/share/nvim/site/autoload'] | path_join }}"
    state: directory
    mode: '0755'
  become:  true

- name: Download vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ [home, '.local/share/nvim/site/autoload/plug.vim'] | path_join }}"
    mode: '0644'
  become:  true

- name: Install Vim plugins via vim-plug
  ansible.builtin.command:
    cmd: nvim --headless +PlugInstall +qall

# TODO: set the variable GITHUB_COPILOT_TOKEN or GH_COPILOT_TOKEN in the environment to the github token
