# Install Cargo
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - rust

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
  when: cargo_exists is failed

- name: Install yazi
  community.general.cargo:
    name: "{{ item }}"
    locked: true
  loop:
    - yazi-fm
    - yazi-cli

- name: Check if navi is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/navi"
  register: navi_installed

- name: Install navi if not installed
  community.general.cargo:
    name: "{{ item }}"
    locked: true
  loop:
    - navi
  when: not navi_installed.stat.exists
