---
# Install Cargo
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  environment:
    PATH: "{{ home }}/.cargo/bin:{{ path }}"


- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  when: cargo_exists is failed

- name: Install yazi
  community.general.cargo:
    name: "{{ item }}"
    locked: true
  environment:
    PATH: "{{ home }}/.cargo/bin:{{ path }}"
  loop:
    - yazi-fm
    - yazi-cli

- name: Install navi if not installed
  community.general.cargo:
    name: "{{ item }}"
    locked: true
  environment:
    PATH: "{{ home }}/.cargo/bin:{{ path }}"
  loop:
    - navi

