- name: Ensure .ssh directory exists.
  file:
    dest: "{{ [home, '.ssh'] | path_join }}"
    mode: 0775
    state: directory

- name: Install ssh key
  copy:
    src: "{{ key }}"
    dest: "{{ [home, key] | path_join }}"
    mode: 0600

- name: Install ssh key public
  copy:
    src: "{{ key }}.pub"
    dest: "{{ [home, key] | path_join }}.pub"
    mode: 0644

- name: Set authorized key took from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', [home, key + '.pub'] | path_join) }}"
  with_fileglob: "{{ home }}/.ssh/*.pub"