# tmux configuration
- name: Ensure tmux is installed.
  package:
    name: tmux
    state: present
  become: true

- name: Create .tmux.conf
  copy:
    src: .tmux.conf
    dest: "{{ [home, '.tmux.conf'] | path_join }}"
    mode: 0644

- name: Add tmux-sessionizer to ~/.local/bin
  copy:
    src: tmux-sessionizer 
    dest: "{{ [home, '.local', 'bin', 'tmux-sessionizer'] | path_join }}"
    mode: 0755