# tmux configuration
- name: Ensure tmux is installed.
  package:
    name: tmux
    state: present
  become: true

- name: Install the Tmux plugin manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: "{{ home }}/.tmux/plugins/tpm"

- name: Install tmux plugins
  ansible.builtin.shell: ~/.tmux/plugins/tpm/bin/install_plugins
