# Zsh configuration
- name: Ensure zsh is installed.
  package:
    name: zsh 
    state: present
  become: true

- name: Ensure ruby is installed (for colorls).
  package:
    name:
      - ruby
      - ruby-dev
      - ruby-colorize
    state: present
  become: true

- name: Check current shell
  command: echo $SHELL
  register: shell
  changed_when: false

- name: Change shell to zsh
  shell: chsh -s $(which zsh) "{{ user }}"
  args:
    executable: /bin/bash
  become: true
  when: "'zsh' not in shell.stdout" 

- debug:
    msg: "Using shell {{ lookup('env', 'SHELL') }}"

# Oh-my-zsh installation
- name: Install oh-my-zsh
  get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install_oh_my_zsh.sh
    mode: '0755'
  become: true

- name: Run oh-my-zsh installation script
  shell: sh /tmp/install_oh_my_zsh.sh --unattended
  args:
    creates: "{{ home }}/.oh-my-zsh"

- name: Ensure .oh-my-zsh custom plugins directory exists
  ansible.builtin.file:
    path: "{{ home }}/.oh-my-zsh/custom/plugins"
    state: directory
    owner: "{{ user }}"

# Zsh plugins
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install zsh-history-substring-search
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-history-substring-search.git'
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-history-substring-search"

- name: Install powerlevel10k 
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k'
    dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k" # to use this, we need to change the theme to: powerlevel10k/powerlevel10k

- debug: 
    msg: "Using the zsh theme {{ zsh_theme }}"

- name: Create .zshr 
  ansible.builtin.template:
    src: templates/.zshrc.j2
    dest: "{{ [home, '.zshrc'] | path_join }}"
    mode: 0644
  vars: 
    zsh_plugins: "web-search vi-mode zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search"

- name: Read contents matching regex from ~/.zshrc
  ansible.builtin.command:
    cmd: grep -E '^(plugins=|source)' "{{ home }}/.zshrc"
  register: grep_result
  changed_when: false

- debug:
    msg: "The pluings being used in .zshrc are {{ grep_result.stdout_lines }} "

- name: Create .p10k.zsh
  copy:
    src: .p10k.zsh
    dest: "{{ [home, '.p10k.zsh'] | path_join }}"
    mode: 0644